### ISSUE TITLE
标签可以复制的功能

### ISSUE THREAD

**Issue by FirminSun** [skiars/sd-tagtool#3]
Hi，
可以添加一个标签复制的功能吗？
![image](https://github.com/skiars/sd-tagtool/assets/16684985/efc84a72-3939-437f-8d47-be02b77c9895)

**Comment by skiars** [comment]
嗯，我有空试试

**Comment by FirminSun** [comment]
嗯，还有查找替换功能，比如：chinese clothes 通常在打标程序里面识别为Japanese clothes。

**Comment by skiars** [comment]
这两个功能做好了

**Comment by FirminSun** [comment]
> 这两个功能做好了

@skiars  非常感谢您的更新，我很喜欢您这个工具，一直在用。

**Comment by skiars** [comment]
感谢支持！
