### ISSUE TITLE
linux中图像标签位置无法显示

### ISSUE THREAD

**Issue by yelpeach** [skiars/sd-tagtool#4]
如图，系统：Ubuntu20发行版，ZorinOS16.3
![image](https://github.com/skiars/sd-tagtool/assets/130973382/66e14401-696d-45c2-a7cf-ae6a9d41537d)
盲点可以显示某个标签，可能是系统颜色导致的？
![image](https://github.com/skiars/sd-tagtool/assets/130973382/4eefbc94-f52d-441e-9530-6098c5c6d85f)

**Comment by skiars** [comment]
你试下在 Windows 上跑同样的场景看看？

**Comment by yelpeach** [comment]
感谢回复，用您打包好的exe，在windows下跑没有问题，是正常的。在linux里我试了deb和AppImage都有这个问题

**Comment by skiars** [comment]
可能是发行版带的浏览器内核兼容性有问题，你要是方便的话直接在 Windows 上用吧，我在 Linux 上跑也是一堆坑。

**Comment by yelpeach** [comment]
好的，感谢分享
