### ISSUE TITLE
Can't load Folder

### ISSUE THREAD

**Issue by 5chlupp** [skiars/sd-tagtool#5]
Hi, thanks for the app I think it's great to have especially on Mac OS. But the app can't load my folder with pictures under Windows 11 and Mac OS when I select it via the open dialogue. BooruDatasetTagManager can open the folder. Am I doing something wrong? 
Thank you! 

sd-tagtool v1.2.0

**Comment by skiars** [comment]
Are there any error messages?

**Comment by 5chlupp** [comment]
no, no Error massage. Maybe my Screenshots can help.
in the Folder are .jpeg files and .txt files. 
.png files can be loaded but your app can't load .jpeg files? :)

![1](https://github.com/skiars/sd-tagtool/assets/58439006/46b790d4-4278-465c-b19e-3d92de77cdcb)
![2](https://github.com/skiars/sd-tagtool/assets/58439006/a9e07d63-0a45-49a9-8ded-a4c9316f8ff2)
![3](https://github.com/skiars/sd-tagtool/assets/58439006/10547d9f-5cdb-4d2e-b98d-ff1ca5653d6a)

**Comment by skiars** [comment]
Yes, I didn't add the jpeg image support 🤣. I'll add it later.

**Comment by skiars** [comment]
Please check v1.2.1 version.

**Comment by 5chlupp** [comment]
Thank you! 👑 .jpeg + .txt works in v1.2.1 😃

But only tested under Mac OS 14…
