### ISSUE TITLE
Since version 1.2.1 I can no longer write in the text fields on Mac OS

### ISSUE THREAD

**Issue by 5chlupp** [skiars/sd-tagtool#6]
Hello,
Since version 1.2.1 I can no longer write in the text fields on Mac OS.
In version 1.2.0 it worked under Mac OS and Windows 11.
Windows not tested with version 1.2.1.
Best, 
:)

**Comment by skiars** [comment]
v1.2.2 should work.

**Comment by 5chlupp** [comment]
Tanke you, it works in v.1.2.2! 🎈
Tested only under Mac OS.
